# Generated by Django 4.2.11 on 2025-06-09 21:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maincategory',
            options={'ordering': ['name'], 'verbose_name': 'Main Category', 'verbose_name_plural': 'Main Categories'},
        ),
        migrations.AlterModelOptions(
            name='nominationcategory',
            options={'ordering': ['main_category', 'name'], 'verbose_name': 'Nomination Category', 'verbose_name_plural': 'Nomination Categories'},
        ),
        migrations.AlterModelOptions(
            name='nominee',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Nominee', 'verbose_name_plural': 'Nominees'},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ['-created_at'], 'verbose_name': 'Vote', 'verbose_name_plural': 'Votes'},
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='maincategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maincategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='maincategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='nominationcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nominationcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='nominee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nominee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voter_identifier',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voter_type',
            field=models.CharField(choices=[('web', 'Web'), ('ussd', 'USSD'), ('sms', 'SMS')], max_length=10),
        ),
        migrations.AddIndex(
            model_name='nominee',
            index=models.Index(fields=['approved'], name='nominations_approve_5d01da_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['voter_identifier'], name='nominations_voter_i_67ce4a_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['created_at'], name='nominations_created_77e009_idx'),
        ),
        migrations.AddConstraint(
            model_name='nominationcategory',
            constraint=models.UniqueConstraint(fields=('main_category', 'name'), name='unique_category_name_per_main_category'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('nominee', 'voter_identifier'), name='unique_vote_per_nominee'),
        ),
    ]
