# Generated by Django 4.2.11 on 2025-06-27 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMessage',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('from_number', models.CharField(max_length=15, verbose_name='Sender Number')),
                ('message_body', models.TextField(verbose_name='Message Content')),
                ('approved', models.BooleanField(default=False, verbose_name='Approved Status')),
                ('declined', models.BooleanField(default=False, verbose_name='Declined Status')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Creation Date')),
                ('moderated_at', models.DateTimeField(blank=True, null=True, verbose_name='Moderation Date')),
                ('source', models.CharField(choices=[('sms', 'SMS'), ('web', 'Web'), ('api', 'API'), ('other', 'Other')], default='sms', max_length=10, verbose_name='Message Source')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('moderated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Moderated By')),
            ],
            options={
                'verbose_name': 'historical SMS Message',
                'verbose_name_plural': 'historical SMS Messages',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_number', models.CharField(max_length=15, verbose_name='Sender Number')),
                ('message_body', models.TextField(verbose_name='Message Content')),
                ('approved', models.BooleanField(default=False, verbose_name='Approved Status')),
                ('declined', models.BooleanField(default=False, verbose_name='Declined Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('moderated_at', models.DateTimeField(blank=True, null=True, verbose_name='Moderation Date')),
                ('source', models.CharField(choices=[('sms', 'SMS'), ('web', 'Web'), ('api', 'API'), ('other', 'Other')], default='sms', max_length=10, verbose_name='Message Source')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_messages', to=settings.AUTH_USER_MODEL, verbose_name='Moderated By')),
            ],
            options={
                'verbose_name': 'SMS Message',
                'verbose_name_plural': 'SMS Messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['approved', 'declined'], name='messages_ap_approve_a15fa9_idx'), models.Index(fields=['created_at'], name='messages_ap_created_78ae4c_idx'), models.Index(fields=['source'], name='messages_ap_source_2c7dcd_idx'), models.Index(fields=['moderated_by'], name='messages_ap_moderat_4c811d_idx')],
            },
        ),
    ]
