# Generated by Django 4.2.11 on 2025-06-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0004_historicalmessage_declined_message_declined'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalmessage',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical SMS Message', 'verbose_name_plural': 'historical SMS Messages'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at'], 'verbose_name': 'SMS Message', 'verbose_name_plural': 'SMS Messages'},
        ),
        migrations.AlterField(
            model_name='historicalmessage',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved Status'),
        ),
        migrations.AlterField(
            model_name='historicalmessage',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='historicalmessage',
            name='declined',
            field=models.BooleanField(default=False, verbose_name='Declined Status'),
        ),
        migrations.AlterField(
            model_name='historicalmessage',
            name='from_number',
            field=models.CharField(max_length=15, verbose_name='Sender Number'),
        ),
        migrations.AlterField(
            model_name='historicalmessage',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalmessage',
            name='message_body',
            field=models.TextField(verbose_name='Message Content'),
        ),
        migrations.AlterField(
            model_name='message',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved Status'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='message',
            name='declined',
            field=models.BooleanField(default=False, verbose_name='Declined Status'),
        ),
        migrations.AlterField(
            model_name='message',
            name='from_number',
            field=models.CharField(max_length=15, verbose_name='Sender Number'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_body',
            field=models.TextField(verbose_name='Message Content'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['approved', 'declined'], name='messages_ap_approve_a15fa9_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['created_at'], name='messages_ap_created_78ae4c_idx'),
        ),
    ]
