# Generated by Django 4.2.11 on 2025-06-22 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messages_app', '0005_alter_historicalmessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmessage',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Moderation Date'),
        ),
        migrations.AddField(
            model_name='historicalmessage',
            name='moderated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Moderated By'),
        ),
        migrations.AddField(
            model_name='historicalmessage',
            name='source',
            field=models.CharField(choices=[('sms', 'SMS'), ('web', 'Web'), ('api', 'API'), ('other', 'Other')], default='sms', max_length=10, verbose_name='Message Source'),
        ),
        migrations.AddField(
            model_name='message',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Moderation Date'),
        ),
        migrations.AddField(
            model_name='message',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_messages', to=settings.AUTH_USER_MODEL, verbose_name='Moderated By'),
        ),
        migrations.AddField(
            model_name='message',
            name='source',
            field=models.CharField(choices=[('sms', 'SMS'), ('web', 'Web'), ('api', 'API'), ('other', 'Other')], default='sms', max_length=10, verbose_name='Message Source'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['source'], name='messages_ap_source_2c7dcd_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['moderated_by'], name='messages_ap_moderat_4c811d_idx'),
        ),
    ]
