# Generated by Django 4.2.11 on 2025-06-27 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nominations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Voting Session',
                'verbose_name_plural': 'Voting Sessions',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['is_active'], name='voting_vote_is_acti_79e3b8_idx'), models.Index(fields=['start_time', 'end_time'], name='voting_vote_start_t_103184_idx')],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_identifier', models.CharField(max_length=100)),
                ('voter_type', models.CharField(choices=[('ussd', 'USSD'), ('web', 'Web'), ('mobile', 'Mobile App')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('nominee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting_votes', to='nominations.nominee')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='voting.votesession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vote',
                'verbose_name_plural': 'Votes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['voter_identifier'], name='voting_vote_voter_i_44c37a_idx'), models.Index(fields=['created_at'], name='voting_vote_created_f40b96_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('session', 'voter_identifier'), name='unique_voter_per_session'),
        ),
    ]
