# Generated by Django 4.2.11 on 2025-06-09 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0002_alter_maincategory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ['-created_at'], 'verbose_name': 'Vote', 'verbose_name_plural': 'Votes'},
        ),
        migrations.AlterModelOptions(
            name='votesession',
            options={'ordering': ['-start_time'], 'verbose_name': 'Voting Session', 'verbose_name_plural': 'Voting Sessions'},
        ),
        migrations.RemoveField(
            model_name='votesession',
            name='active',
        ),
        migrations.AddField(
            model_name='vote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='votesession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='votesession',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='votesession',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='votesession',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='votesession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='nominee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting_votes', to='nominations.nominee'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='voting.votesession'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voter_type',
            field=models.CharField(choices=[('ussd', 'USSD'), ('web', 'Web'), ('mobile', 'Mobile App')], max_length=50),
        ),
        migrations.AlterField(
            model_name='votesession',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['voter_identifier'], name='voting_vote_voter_i_44c37a_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['created_at'], name='voting_vote_created_f40b96_idx'),
        ),
        migrations.AddIndex(
            model_name='votesession',
            index=models.Index(fields=['is_active'], name='voting_vote_is_acti_79e3b8_idx'),
        ),
        migrations.AddIndex(
            model_name='votesession',
            index=models.Index(fields=['start_time', 'end_time'], name='voting_vote_start_t_103184_idx'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('session', 'voter_identifier'), name='unique_voter_per_session'),
        ),
    ]
