name: Deploy to VPS

on:
  push:
    branches: [production]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/tgk/code-base/StreamSMS
            source /home/tgk/code-base/venvs/streamsms/bin/activate
            git -C /home/tgk/code-base/Deployments/StreamSMS.git pull origin production
            pip install -r requirements.txt
            python manage.py migrate
            python manage.py collectstatic --noinput

            echo '${{ secrets.SUDO_PASSWORD }}' | sudo -S supervisorctl restart streamsms
